### ISSUE TITLE
Trouble opening pop-up from within editor iframe

### ISSUE THREAD

**Issue by wardpenney** [contentful/widget-sdk#106]
Hi!

I am trying to open a Filepicker in a pop-up from within a custom widget. It works locally, but does not work when editing the Entry on contentful.com. 

I have a sample repo here [wardpenney/contentful-issue-widget-with-pop-up](https://github.com/wardpenney/contentful-issue-widget-with-pop-up) with instructions on how to view it working locally, and not work in prod.

Thanks for all your help!

This is carried over from support ticket at https://support.contentful.com/hc/en-us/requests/7185?flash_digest=f9adcbaeba6855987cc70c14e325063d55300b9f

**Comment by geigerzaehler** [comment]
Hi Ward! The issue with the filepicker is not specific to our environment. Unfortunately there is nothing we can do to fix it on our side.

You can very easily reproduce the issue without using Contentful at all. Just create a small `index.html` file
~~~html
<!doctype html>
<iframe src="dist/index.html" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox">
~~~
When you open it in a browser you’ll see the same error message as in the Contentful Web App
> `Uncaught SecurityError: Failed to set the 'cookie' property on 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.`

The cause of the problem is that we [sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) the the IFrame and do not set the  `allow-same-origin` flag. This prevents any code inside the IFrame from setting cookies. We cannot lift these restrictions since they enforce boundaries between the Contentful App and any custom widget. Doing so would seriously compromise security.

I suggest that you contact the filepicker support and ask them how to make their library work in a sandboxed IFrame.

**Comment by wardpenney** [comment]
Ok thanks @geigerzaehler for the information! I am already in contact with them and hopefully we can resolve it. Feel free to close this Issue.
